const dummyParties = [
  {
    id: 0,
    title: 'BHC 뿌링클 오늘 7시',
    createTime: '2022-02-14T05:25:17.410Z',
    joinNumber: 2,
    goalNumber: 4,
    status: 'order',
    place: 'SINCHON',
    hashtags: ['치킨', 'BHC'],
  },
  {
    id: 1,
    title: '내일 점심에 버거킹 드실분',
    createTime: '2022-02-15T14:25:17.410Z',
    joinNumber: 1,
    goalNumber: 2,
    status: 'soon',
    place: 'YEONHUI',
    hashtags: ['버거킹', '햄버거'],
  },
  {
    id: 2,
    title: '푸라닭 콘소메이징 맛있어요',
    createTime: '2022-02-15T15:25:17.410Z',
    joinNumber: 3,
    goalNumber: 3,
    status: 'full',
    place: 'CHANGCHEON',
    hashtags: ['치킨', '푸라닭'],
  },
  {
    id: 3,
    title: '초밥 시켜먹어요',
    createTime: '2022-02-15T18:25:17.410Z',
    joinNumber: 1,
    goalNumber: 4,
    status: 'cancel',
    place: 'SINCHON',
    hashtags: ['초밥', '스시'],
  },
  {
    id: 4,
    title: '떡볶이 ㄱ?',
    createTime: '2022-02-16T05:25:17.410Z',
    joinNumber: 1,
    goalNumber: 2,
    status: 'on',
    place: 'CHANGCHEON',
    hashtags: ['떡볶이', '엽떡', '국대'],
  },
];

export default dummyParties;
