const dummyParty = [
  {
    ownerNickname: '재호',
    title: 'BHC 뿌링클 오늘 7시',
    createTime: '2022-02-14T05:25:17.410Z',
    joinNumber: 2,
    goalNumber: 4,
    status: 'order',
    place: 'SINCHON',
    hashtags: ['치킨', 'BHC', '배달비', '뿌링클'],
    content: '오늘 7시에 BHC에서 배달 나눠 시키실 분 구합니다. 창서초 앞에서 픽업해요~',
  },
  {
    ownerNickname: '현경',
    title: '내일 점심에 버거킹 드실분',
    createTime: '2022-02-15T14:25:17.410Z',
    joinNumber: 1,
    goalNumber: 2,
    status: 'soon',
    place: 'YEONHUI',
    hashtags: ['버거킹', '햄버거'],
    content: '내일 버거킹 시켜서 서문 근처에서 받으실분 구합니다',
  },
  {
    ownerNickname: '건호',
    title: '푸라닭 콘소메이징 맛있어요ㅛㅛㅛㅛㅛㅛ',
    createTime: '2022-02-15T15:25:17.410Z',
    joinNumber: 3,
    goalNumber: 3,
    status: 'full',
    place: 'CHANGCHEON',
    hashtags: ['치킨', '푸라닭'],
    content: '푸라닭 개꿀맛',
  },
  {
    ownerNickname: '태준',
    title: '초밥 시켜먹어요',
    createTime: '2022-02-15T18:25:17.410Z',
    joinNumber: 1,
    goalNumber: 4,
    status: 'cancel',
    place: 'SINCHON',
    hashtags: ['초밥', '스시'],
    content: '학교에서 초밥 시켜서 나눠 받으실분!',
  },
  {
    ownerNickname: '재호',
    title: '떡볶이 ㄱ?',
    createTime: '2022-02-16T15:59:17.410Z',
    joinNumber: 1,
    goalNumber: 2,
    status: 'on',
    place: 'CHANGCHEON',
    hashtags: ['떡볶이', '엽떡', '국대'],
    content: '엽떡이나 국대 나눠 시키실 분 구합니다. 우체국 근처',
  },
];

export default dummyParty;
